ecom/core/urls.py
from django.urls import path, include
from core import views
 
app_name = 'core'

urlpatterns = [
    # HomePage
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),
    path("products/details/<pid>/", views.product_detail_view, name="product-detail"),
    
    # Category
    path("category/", views.subcategory_list_view, name="category-list"),
    path("category/<scid>/", views.subcategory_product_list_view, name="category-product-list"),
    
    # Vendor
    path("vendor/", views.vendor_list_view, name="vendor-list"),
    path("vendor/detail/<vid>", views.vendor_detail_view, name="vendor-detail"),
    
    # Tags
    path("products/tag/<slug:tag_slug>/",views.tag_list,name="tags"),
    
    
    # Reviews
    path("ajax-add-review/<int:pid>",views.ajax_add_review,name="ajax-add-review"),
    
    # search
    
    path("search/", views.search_view, name="search"),
    
    # filter
    path("filter-products/", views.filter_product, name="filter-product"),
    
    # Add to Cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    
    path("cart/",views.cart_view, name="cart"),
    path("delete-from-cart/",views.delete_item_cart, name="delete-from-cart"),
    path("update-cart/",views.update_item_cart, name="update-cart"),
    
    # Checkout page
    path("checkout/",views.checkout_view, name="checkout"),
    
    # PayPal
    path("paypal/",include("paypal.standard.ipn.urls")),
    
    # Payment Completed
    path("payment-completed/",views.payment_completed_view, name="payment-completed"),
    
    
    # Payment Failed
    
    path("payment-failed/",views.payment_failed_view, name="payment-failed"),
    
    
    # Customer Dashboard
    path("customer/",views.customer_dashboard, name="customer-dashboard"),
    
]

ecom/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Wirte review"}))
    
    class Meta:
        model = ProductReview
        fields = ['review','rating']

ecom/core/views.py
from django.shortcuts import render, get_object_or_404
from core.models import *
from django.db.models import Count, Avg
from core.forms import ProductReviewForm
from taggit.models import Tag
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
# Create your views here.

def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published",featured=True)
    
    context = {
        'products':products
    }
    return render(request,'core/index.html',context)


def product_list_view(request):
    products = Product.objects.filter(product_status="published")
    
    context = {
        'products':products
    }
    return render(request,'core/product_list.html',context)
    

def subcategory_list_view(request):
    categories = Category.objects.all()
    
    subcategories = SubCategory.objects.all()
    # subcategories = SubCategory.objects.all().annotate(product_count=Count("product"))
    
    context ={
        'subcategories':subcategories,
        'categories':categories
    }
    return render(request, 'core/category-list.html',context)

def subcategory_product_list_view(request, scid):
    category = Category.objects.all()
    subcategory = SubCategory.objects.get(scid = scid)
    products = Product.objects.filter(product_status="published",subcategory=subcategory)
    # products = Product.objects.filter(product_status="published")
    
    context = {
        'products':products,
        'subcategory':subcategory,
        'category':category
    }
    return render(request, "core/category-product-list.html", context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        'vendors':vendors
    }
    return render(request, 'core/vendor-list.html', context)


def vendor_detail_view(request,vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor,product_status="published")
    subcategories = SubCategory.objects.all()
    context = {
        'vendor':vendor,
        'products':products,
        'subcategories':subcategories
    }
    return render(request, 'core/vendor-detail.html', context)


def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)
    p_image = product.p_images.all()
    products = Product.objects.filter(subcategory=product.subcategory).exclude(pid=pid)
    
    # getting all reviews related a produtc
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    
    # Getting average review
    
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    # Product Review FOrm
    review_form = ProductReviewForm()
    
    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        
        if user_review_count > 0:
            make_review = False
            
    context = {
        'product':product,
        'p_image':p_image,
        'reviews':reviews,
        'make_review':make_review,
        'review_form':review_form,
        'average_rating':average_rating,
        'products':products
    }
    return render(request, 'core/product-detail.html',context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products":products,
        "tag":tag
    }
    return render(request, "core/tag.html", context)

def ajax_add_review(request, pid):
    product =Product.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user=user,
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    
    context = {
        'user':user.username,
        'review':request.POST['review'],
        'rating':request.POST['rating'],
    }
    
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'average_reviews':average_reviews
        }
    )


def search_view(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query,description__icontains=query).order_by("-date")
    
    context = {
        'products': products,
        'query':query,
    }
    
    return render(request, 'core/search.html', context)

def filter_product(request):
    subcategories = request.GET.getlist('subcategory[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    
    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)
    
    if len(subcategories) > 0:
        products = products.filter(subcategory__id__in=subcategories).distinct()
        
    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    context = {
        "products": products,
        
    }
    data = render_to_string("core/async/products-list.html",context)
    return JsonResponse({"data": data})
    

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],
    }
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({'data':request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj'])})
            

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, 'core/cart-view.html',{'cart_data':request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']) ,'cart_total_amount':cart_total_amount})            
    else:
        # return render(request, 'core/cart-view.html',{'cart_data':'','totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})            
        messages.warning(request,"Your cart is Empty")
        return redirect("core:index")

def delete_item_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            
    context = render_to_string("core/async/cart-list.html",{'cart_data':request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']) ,'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context,'totalcartitems':len(request.session['cart_data_obj'])})

# Update Cart List
def update_item_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            
    context = render_to_string("core/async/cart-list.html",{'cart_data':request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']) ,'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context,'totalcartitems':len(request.session['cart_data_obj'])})


@login_required
def checkout_view(request):
    host = request.get_host()
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '200',
        'item_name': "Order-Item-No-3",
        'invoice': "INVOICE_NO-3",
        'currency_code': 'INR', 
        'notify_url': 'http://{}{}'.format(host, reverse("core:paypal-ipn")),
        'return_url': 'http://{}{}'.format(host, reverse("core:payment-completed")),
        'cancel_url': 'http://{}{}'.format(host, reverse("core:payment-failed")),
    }
    

ecom/templates/core/payment-completed.html
{% extends 'partials/base copy.html' %}
{% load static %}

{% block content1 %}

<div class="invoice invoice-content invoice-6">
    <div class="back-top-home hover-up mt-30 ml-30">
        <a class="hover-up" href="index.html"><i class="fi-rs-home mr-5"></i> Homepage</a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="invoice-inner">
                    <div class="invoice-info" id="invoice_wrapper">
                        <div class="invoice-header">
                            <div class="invoice-icon">
                                <img src="{% static 'assets/fonts/icon-invoice.svg' %}" class="img-fluid" alt>
                            </div>
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <div class="logo">
                                        <a href="index.html" class="mr-20"><img src="{% static 'assets/fonts/logo.svg' %}" alt="logo"></a>
                                    </div>
                                </div>
                                <div class="col-md-6 text-end">
                                    <h2 class="mb-0">INVOICE</h2>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <div class="text">
                                        205 North, Suite 810, Chicago, USA<br>
                                        <abbr title="Phone">Phone:</abbr> (+123) 456-7890<br>
                                    </div>
                                </div>
                                <div class="col-md-6 text-end">
                                    <strong class="text-brand">Webz Poland</strong> <br>
                                    Madalinskiego 871-101 Szczecin, Poland<br>
                                    <abbr title="Email">Email: </abbr><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="e6888089a69183849cc885898bc8968a">[email protected]</a>
                                </div>
                            </div>
                            <div class="row mt-20">
                                <div class="col-12">
                                    <div class="hr mb-10"></div>
                                </div>
                                <div class="col-lg-4">
                                    <strong class="text-brand"> Invoice No:</strong> 789654
                                </div>
                                <div class="col-lg-4">
                                    <strong class="text-brand"> Issue Date:</strong> 20 April, 2022
                                </div>
                                <div class="col-lg-4">
                                    <strong class="text-brand"> Payment Method:</strong> Credit Card
                                </div>
                                <div class="col-12">
                                    <div class="hr mt-10"></div>
                                </div>
                            </div>
                        </div>
                        <div class="invoice-center">
                            <div class="table-responsive">
                                <table class="table table-striped invoice-table">
                                    <thead class="bg-active">
                                        <tr>
                                            <th>Item Item</th>
                                            <th class="text-center">Unit Price</th>
                                            <th class="text-center">Quantity</th>
                                            <th class="text-right">Amount</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product_id, item in cart_data.items %}
                                        <tr>
                                            <td>
                                                <div class="item-desc-1">
                                                    <span>{{item.title}}</span>
                                                </div>
                                            </td>
                                            <td class="text-center">Rs.{{item.price|floatformat:2}}</td>
                                            <td class="text-center">x{{item.qty}}</td>
                                            <td class="text-right">{% widthratio item.price 1 item.qty %}.00</td>
                                        </tr>
                                        {% endfor %}
                                        
                                        
                                        <tr>
                                            <td colspan="3" class="text-end f-w-600">SubTotal</td>
                                            <td class="text-right">Rs.{{cart_total_amount}}</td>
                                        </tr>
                                        <!-- <tr>
                                            <td colspan="3" class="text-end f-w-600">Tax</td>
                                            <td class="text-right">$85.99</td>
                                        </tr> -->
                                        <tr>
                                            <td colspan="3" class="text-end f-w-600">Grand Total</td>
                                            <td class="text-right f-w-600">Rs.{{cart_total_amount}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="invoice-bottom pb-80">
                            <div class="row">
                                <div class="col-md-6">
                                    <h6 class="mb-15">Invoice Infor</h6>
                                    <p class="font-sm">
                                        <!-- <strong>Issue date:</strong> 20 march, 2022<br> -->
                                        <strong>Invoice To:</strong> {{request.user|title}}<br>
                                        <!-- <strong>Swift Code:</strong> BFTV VNVXS -->
                                    </p>
                                </div>
                                <div class="col-md-6 text-end">
                                    <h6 class="mb-15">Total Amount</h6>
                                    <h3 class="mt-0 mb-0 text-brand">Rs.{{cart_total_amount}}</h3>
                                    <p class="mb-0 text-muted">Taxes Included</p>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-12">
                                    <div class="hr mt-30 mb-30"></div>
                                    <p class="mb-0 text-muted"><strong>Note:</strong>This is computer generated receipt and does not require physical signature.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="invoice-btn-section clearfix d-print-none">
                        <a href="javascript:window.print()" class="btn btn-lg btn-custom btn-print hover-up"> <img src="{% static 'assets/fonts/icon-print.svg' %}" alt> Print </a>
                        <a id="invoice_download_btn" class="btn btn-lg btn-custom btn-download hover-up"> <img src="{% static 'assets/fonts/icon-download.svg' %}" alt> Download </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content1 %}

ecom/templates/core/payment-failed.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<main class="main">
    
    <div class="container mb-80 mt-50">
        
        <div class="row text-center">
            <div class="col-lg-3"></div>
            <div class="col-lg-7 ">
                <h1 class="text-center"><svg xmlns="http://www.w3.org/2000/svg" height="5em" viewBox="0 0 384 512"><style>svg{fill:#ff0000}</style><path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z"/></svg></h1>
                <h2 cl>Payment Failed</h2>
                <a href="{% url 'core:index' %}" class="btn btn-fill-out btn-block mt-30 mb-40">Go Back to Home Page</a>

            </div>
            
        </div>
    </div>
</main>
{% endblock content %}

ecom/templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<main class="main pages mb-80">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Vendors List
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        <div class="container">
            <div class="archive-header-2 text-center">
                <h1 class="display-2 mb-50">Vendors List</h1>
                <div class="row">
                    <div class="col-lg-5 mx-auto">
                        <div class="sidebar-widget-2 widget_search mb-50">
                            <div class="search-form">
                                <form action="#">
                                    <input type="text" placeholder="Search vendors (by name or ID)...">
                                    <button type="submit"><i class="fi-rs-search"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-50">
                <div class="col-12 col-lg-8 mx-auto">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We have <strong class="text-brand">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Mall</a></li>
                                        <li><a href="#">Featured</a></li>
                                        <li><a href="#">Preferred</a></li>
                                        <li><a href="#">Total items</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row vendor-grid">
                {% for v in vendors %}
                <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                    <div class="vendor-wrap style-2 mb-40">
                        <div class="product-badges product-badges-position product-badges-mrg">
                            <span class="hot">Mall</span>
                        </div>
                        <div class="vendor-img-action-wrap">
                            <div class="vendor-img">
                                <a href="{% url 'core:vendor-detail' v.vid %}">
                                    <img class="default-img" src="{{v.image.url}}" alt>
                                </a>
                            </div>
                            <div class="mt-10">
                                <span class="font-small total-product">{{v.product.all.count}} products</span>
                            </div>
                        </div>
                        <div class="vendor-content-wrap">
                            <div class="mb-30">
                                <div class="product-category">
                                    <span class="text-muted">Since {{v.date|date:"Y"}}</span>
                                </div>
                                <h4 class="mb-5"><a href="{% url 'core:vendor-detail' v.vid %}">{{v.title}}</a></h4>
                                <div class="product-rate-cover">
                                    <div class="product-rate d-inline-block">
                                        <div class="product-rating" style="width: 90%"></div>
                                    </div>
                                    <span class="font-small ml-5 text-muted "> ({{v.authentic_rating}}.0)</span>
                                </div>
                                <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                    <ul class="contact-infor text-muted mr-10">
                                        <li><img src="{% static 'assets/fonts/icon-location.svg' %}" alt><strong>Address: </strong> <span>{{v.address}}</span></li>
                                        <li><img src="{% static 'assets/fonts/icon-contact.svg' %}" alt><strong>Call Us:</strong><span>(+91) - {{v.phone}}</span></li>
                                    </ul>
                                </div>
                                <br>
                                <a href="{% url 'core:vendor-detail' v.vid %}" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>

                            </div>
                        </div>
                    </div>
                </div>
                
                {% endfor %}
                
                <!--end vendor card-->
                
            </div>
            <div class="pagination-area mt-20 mb-20">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                        <li class="page-item"><a class="page-link" href="#">6</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</main>
{% endblock content %}